Repository Daggerpov/Spawn-App-iOS-SwiftUI, pull requests merged in 2025-03, with the labels that each got.

#96 72 new tag assignment page done re design
  Spawn-App-iOS-SwiftUI/Assets.xcassets/Spawn_Glow.imageset/Contents.json
  Spawn-App-iOS-SwiftUI/Assets.xcassets/Spawn_Glow.imageset/Spawn_Glow.svg
  Spawn-App-iOS-SwiftUI/Models/FriendTag.swift
  Spawn-App-iOS-SwiftUI/Services/API/MockAPIService.swift
  Spawn-App-iOS-SwiftUI/ViewModels/ChoosingTags/ChoosingTagViewModel.swift
  Spawn-App-iOS-SwiftUI/Views/ChooseTagPopUpView.swift
  Spawn-App-iOS-SwiftUI/Views/Enums/ProfileImageType.swift
  Spawn-App-iOS-SwiftUI/Views/FriendRequestView.swift
  Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tabs/FriendsTabView.swift
  Spawn-App-iOS-SwiftUI/Views/ViewModifiers/ProfileImages.swift
Labels: enhancement

#135 Onboarding Documentation
  README.md
  Spawn-App-iOS-SwiftUI/Models/DTOs/FriendRequest/CreateFriendRequestDTO.swift
  Spawn-App-iOS-SwiftUI/Services/API/APIService.swift
  images/current-app-look-images/event-creation-invite-friends.png
  images/current-app-look-images/event-creation-invite-tags.png
  images/current-app-look-images/event-creation.png
  images/current-app-look-images/event-description-modal.png
  images/current-app-look-images/friends-list.png
  images/current-app-look-images/friends-tab.png
  images/current-app-look-images/map-view.png
  images/current-app-look-images/new-friends-tab.png
  images/current-app-look-images/profile-page.png
  images/current-app-look-images/tag-deletion.png
  images/current-app-look-images/tags-for-new-friend.png
  images/current-app-look-images/tags-tab.png
  images/current-app-look-images/tags-view.png
  images/onboarding-images/image-1.png
  images/onboarding-images/image-10.png
  images/onboarding-images/image-11.png
  images/onboarding-images/image-12.png
  images/onboarding-images/image-13.png
  images/onboarding-images/image-14.png
  images/onboarding-images/image-15.png
  images/onboarding-images/image-16.png
  images/onboarding-images/image-17.png
  images/onboarding-images/image-18.png
  images/onboarding-images/image-19.png
  images/onboarding-images/image-2.png
  images/onboarding-images/image-3.png
  images/onboarding-images/image-4.png
  images/onboarding-images/image-5.png
  images/onboarding-images/image-6.png
  images/onboarding-images/image-7.png
  images/onboarding-images/image-8.png
  images/onboarding-images/image-9.png
  images/onboarding-images/image.png
Labels: documentation

#137 Last (hopefully) DTO Adjustments
  Spawn-App-iOS-SwiftUI/Models/DTOs/Event/EventCreationDTO.swift
  Spawn-App-iOS-SwiftUI/Models/DTOs/Event/FullFeedEventDTO.swift
  Spawn-App-iOS-SwiftUI/Models/DTOs/FriendRequest/FetchFriendRequestDTO.swift
  Spawn-App-iOS-SwiftUI/Models/DTOs/FriendTag/FriendTagCreationDTO.swift
  Spawn-App-iOS-SwiftUI/Models/DTOs/FriendTag/FullFriendTagDTO.swift
  Spawn-App-iOS-SwiftUI/Models/DTOs/FullEventChatMessageDTO.swift
  Spawn-App-iOS-SwiftUI/Models/DTOs/User/BaseUserDTO.swift
  Spawn-App-iOS-SwiftUI/Models/Event.swift
  Spawn-App-iOS-SwiftUI/Services/API/APIService.swift
  Spawn-App-iOS-SwiftUI/Services/API/MockAPIService.swift
  Spawn-App-iOS-SwiftUI/Services/FormatterService.swift
  Spawn-App-iOS-SwiftUI/ViewModels/ChoosingTags/ChoosingTagViewModel.swift
  Spawn-App-iOS-SwiftUI/ViewModels/Event/EventCardViewModel.swift
  Spawn-App-iOS-SwiftUI/ViewModels/Event/EventCreationViewModel.swift
  Spawn-App-iOS-SwiftUI/ViewModels/Event/EventDescriptionViewModel.swift
  Spawn-App-iOS-SwiftUI/ViewModels/Event/EventInfoViewModel.swift
  Spawn-App-iOS-SwiftUI/ViewModels/FeedViewModel.swift
  Spawn-App-iOS-SwiftUI/ViewModels/FriendsTabViewModel.swift
  Spawn-App-iOS-SwiftUI/ViewModels/TagsViewModel.swift
  Spawn-App-iOS-SwiftUI/ViewModels/UserAuthViewModel.swift
  Spawn-App-iOS-SwiftUI/Views/ChooseTagPopUpView.swift
  Spawn-App-iOS-SwiftUI/Views/EventCardView.swift
  Spawn-App-iOS-SwiftUI/Views/EventCreationView.swift
  Spawn-App-iOS-SwiftUI/Views/EventDescriptionView.swift
  Spawn-App-iOS-SwiftUI/Views/FeedView.swift
  Spawn-App-iOS-SwiftUI/Views/FriendRequestView.swift
  Spawn-App-iOS-SwiftUI/Views/FriendsView.swift
  Spawn-App-iOS-SwiftUI/Views/MapView.swift
  Spawn-App-iOS-SwiftUI/Views/ProfileView.swift
  Spawn-App-iOS-SwiftUI/Views/SubComponents/EventCreationFriendsViews/InviteFriendsView.swift
  Spawn-App-iOS-SwiftUI/Views/SubComponents/EventCreationFriendsViews/InviteTagsView.swift
  Spawn-App-iOS-SwiftUI/Views/SubComponents/EventCreationFriendsViews/InviteView.swift
  Spawn-App-iOS-SwiftUI/Views/SubComponents/EventInfoViews/EventCardTopRowView.swift
  Spawn-App-iOS-SwiftUI/Views/SubComponents/EventInfoViews/EventInfoView.swift
  Spawn-App-iOS-SwiftUI/Views/SubComponents/EventInfoViews/ParticipantsImagesView.swift
  Spawn-App-iOS-SwiftUI/Views/SubComponents/FeedSubViews/BottomNavButtonView.swift
  Spawn-App-iOS-SwiftUI/Views/SubComponents/FeedSubViews/HeaderView.swift
  Spawn-App-iOS-SwiftUI/Views/SubComponents/FeedSubViews/TagButtonView.swift
  Spawn-App-iOS-SwiftUI/Views/SubComponents/FeedSubViews/TagsScrollView.swift
  Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Common/BackButton.swift
  Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tabs/FriendsTabView.swift
  Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/ExpandedTagView.swift
  Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/FriendContainer.swift
  Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/FriendRow.swift
  Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/TagRow.swift
Labels: technical improvements

#140 Build 71: Chat Message Sending Feature + Fixed Event Loading + Added usernames to events
  Spawn-App-iOS-SwiftUI/Models/DTOs/CreateChatMessageDTO.swift
  Spawn-App-iOS-SwiftUI/Models/DTOs/Event/FullFeedEventDTO.swift
  Spawn-App-iOS-SwiftUI/Models/DTOs/FullEventChatMessageDTO.swift
  Spawn-App-iOS-SwiftUI/Services/API/APIService.swift
  Spawn-App-iOS-SwiftUI/Services/API/MockAPIService.swift
  Spawn-App-iOS-SwiftUI/ViewModels/Event/EventCreationViewModel.swift
  Spawn-App-iOS-SwiftUI/ViewModels/Event/EventDescriptionViewModel.swift
  Spawn-App-iOS-SwiftUI/ViewModels/UserAuthViewModel.swift
  Spawn-App-iOS-SwiftUI/Views/Authentication/UserInfoInputView.swift
  Spawn-App-iOS-SwiftUI/Views/EventCardView.swift
  Spawn-App-iOS-SwiftUI/Views/EventCreationView.swift
  Spawn-App-iOS-SwiftUI/Views/EventDescriptionView.swift
  Spawn-App-iOS-SwiftUI/Views/FeedView.swift
  Spawn-App-iOS-SwiftUI/Views/MapView.swift
  Spawn-App-iOS-SwiftUI/Views/ProfileView.swift
  Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/AddFriendToTagView.swift
Labels: bug, enhancement

#159 Bug fixes & Improvements
  Spawn-App-iOS-SwiftUI.xcodeproj/project.pbxproj
  Spawn-App-iOS-SwiftUI.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Spawn-App-iOS-SwiftUI/Services/API/APIService.swift
  Spawn-App-iOS-SwiftUI/ViewModels/UserAuthViewModel.swift
  Spawn-App-iOS-SwiftUI/Views/Authentication/ImagePicker.swift
  Spawn-App-iOS-SwiftUI/Views/Authentication/UserInfoInputView.swift
  Spawn-App-iOS-SwiftUI/Views/Feedback/FeedbackView.swift
  Spawn-App-iOS-SwiftUI/Views/Helpers/SwiftUIImagePicker.swift
  Spawn-App-iOS-SwiftUI/Views/ProfileView.swift
  Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tabs/FriendsTabView.swift
  Spawn-App-iOS-SwiftUI/Views/SubComponents/NewTagsSubViews/Tags/SearchView.swift
  Spawn-App-iOS-SwiftUI/Views/ViewModifiers/ToastModifier.swift
Labels: bug, enhancement
